version: '3'
services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel
    ports:
      - '9000:80'
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - db

  vue:
    build:
      context: ./vue
      dockerfile: Dockerfile
    container_name: vue
    ports:
      - '9001:80'
    volumes:
      - ./vue:/app

  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
